### ISSUE TITLE
`./apollo.sh build_gpu` was not run successfully

### ISSUE THREAD

**Issue by YingkaiD** [AuroAi/carla_apollo_bridge#25]
When I build apollo in the apollo container,  I can't run it.

Here is what I get after I run `./apollo.sh build_gpu` in the apollo container:
`
root@in_dev_docker:/apollo# ./apollo.sh build_gpu
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under GPU mode. GPU is required to run the build.
[INFO] Start building, please wait ...
WARNING: ignoring LD_PRELOAD in environment.
[INFO] Building on x86_64...
[INFO] Building with --jobs=64 --ram_utilization_factor 80 for x86_64
WARNING: ignoring LD_PRELOAD in environment.
INFO: (07-05 11:33:54.312) Found 3741 targets...
Unhandled exception thrown during build; message: /apollo/bazel-out (Operation not supported)
INFO: (07-05 11:33:54.465) Elapsed time: 3267.151s
java.lang.UnsupportedOperationException: /apollo/bazel-out (Operation not supported)
	at com.google.devtools.build.lib.unix.NativePosixFiles.symlink(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.createSymbolicLink(UnixFileSystem.java:327)
	at com.google.devtools.build.lib.vfs.Path.createSymbolicLink(Path.java:856)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.ensureSymbolicLink(FileSystemUtils.java:392)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.ensureSymbolicLink(FileSystemUtils.java:343)
	at com.google.devtools.build.lib.buildtool.OutputDirectoryLinksUtils.createLink(OutputDirectoryLinksUtils.java:195)
	at com.google.devtools.build.lib.buildtool.OutputDirectoryLinksUtils.createOutputDirectoryLinks(OutputDirectoryLinksUtils.java:76)
	at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:366)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:247)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:339)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:67)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:600)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:351)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.UnsupportedOperationException: /apollo/bazel-out (Operation not supported)
	at com.google.devtools.build.lib.unix.NativePosixFiles.symlink(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.createSymbolicLink(UnixFileSystem.java:327)
	at com.google.devtools.build.lib.vfs.Path.createSymbolicLink(Path.java:856)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.ensureSymbolicLink(FileSystemUtils.java:392)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.ensureSymbolicLink(FileSystemUtils.java:343)
	at com.google.devtools.build.lib.buildtool.OutputDirectoryLinksUtils.createLink(OutputDirectoryLinksUtils.java:195)
	at com.google.devtools.build.lib.buildtool.OutputDirectoryLinksUtils.createOutputDirectoryLinks(OutputDirectoryLinksUtils.java:76)
	at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:366)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:247)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:339)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:67)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:600)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:351)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
![image](https://user-images.githubusercontent.com/74713558/124474071-aa011380-ddd2-11eb-8ff6-810e43ee83ea.png)

Can you please help me with this?

**Comment by WhoAmI-kai** [comment]
![image](https://user-images.githubusercontent.com/74713558/124473984-8f2e9f00-ddd2-11eb-867a-1170d36b74ad.png)
