### ISSUE TITLE
bridge,py: syntax error

### ISSUE THREAD

**Issue by pantment** [AuroAi/carla_apollo_bridge#28]
Hello i am trying to run bridge.py but i see this 

Traceback (most recent call last):
  File "run_bridge.py", line 7, in <module>
    from cyber_py import cyber
  File "/apollo/cyber/python/cyber_py/cyber.py", line 26, in <module>
    from google.protobuf.descriptor_pb2 import FileDescriptorProto
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 113
    class DescriptorBase(metaclass=DescriptorMetaclass):
                                  ^
SyntaxError: invalid syntax

**Comment by marcusvinicius178** [comment]
Hi @pantelmen probably you are facing the same issue I have experienced. To solve this you need to follow this:

In USAGE section a pyton error will occur in carla-apollo container, when trying to run the scripts. To solve this, I used the approach from here: https://github.com/carla-simulator/carla/issues/1466 . It  will help:

    • locate .egg-files in carla_apollo_bridge/carla-python0.9.6/carla/dist/
    • change/install python version in conda enviroment which fits closest to an .egg-file (for me carla-0.9.6-py3.5-linux-x86_64.egg -> 3.5)
    • delete all other .egg-files (just for tidiness)
    • extract your .egg-file, e.g. carla-0.9.6-py3.5-linux-x86_64

    • create setup.py inside the folder (carla-0.9.6-py3.5-linux-x86_64) with the following content:
```
from distutils.core import setup
setup(name='carla',
      version='0.9.6', #doesn't matter I guess
      py_modules=['carla'],
      )
```
    • then you can install the carla-python-package via pip:
`pip install -e ~/carla_apollo_bridge/carla-python-0.9.6/carla/dist/carla-0.9.6-py3.5-linux-x86_64`
That solved it for me. I don't even need the egg-path-appending-stuff, w
